### ISSUE TITLE
Uploads for contributor users

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#115]
Hey @coffeejunk my student is having issues with the mass upload and I think it may be associated with his user class. He is designated as a contributor and was able to upload prior to porting over to Sharkipedia from SharkTraits. I tested with his file and I was able to upload it to the automated checks stage without issue. When Aaron chooses the file on his computer the file window is highlighted in red and the the upload button is greyed out. I checked his status and he is still listed as contributor. Any help would be appreciated...
<img width="1676" alt="Screen Shot 2020-07-23 at 11 24 17 AM" src="https://user-images.githubusercontent.com/4634830/88306930-b71c1400-cce1-11ea-8bcd-65bfadec2b79.png">

<img width="1680" alt="Screen Shot 2020-07-23 at 12 36 43 PM" src="https://user-images.githubusercontent.com/4634830/88306961-c00ce580-cce1-11ea-9a33-71fd7011154e.png">

**Comment by coffeejunk** [comment]
Hm very odd, his user class shouldn't have anything to do with that form. This looks like the upload is failing for some unclear reason.

Can you:
1. open the developer console (option+cmd+i and click on console) 
2. reload the form
3. try to upload the file again
4. show me a screenshot of what's going on in the developer console?

**Comment by creeas** [comment]
should I do this using while logged in as the contributor or as admin? I didn't have any issues myself when I was logged in and uploaded the exact same file...

**Comment by coffeejunk** [comment]
As the contributor and ideally with Aaron's computer.

**Comment by creeas** [comment]
Will do. I just tried on my computer with his credentials and it worked so the issue must be on his end. I will have him follow the steps you sent and report back...

**Comment by creeas** [comment]
Here is what he got on his computer. Looks like blocked by CORS policy.
<img width="1075" alt="Screen Shot 2020-07-23 at 1 10 53 PM" src="https://user-images.githubusercontent.com/4634830/88310480-1714b980-cce6-11ea-9e95-8bf29638e570.png">

**Comment by creeas** [comment]
<img width="1073" alt="Screen Shot 2020-07-23 at 1 13 52 PM" src="https://user-images.githubusercontent.com/4634830/88310725-635ff980-cce6-11ea-8b08-5ffc1427d9de.png">

**Comment by coffeejunk** [comment]
Can you try again on sharkipedia.org instead of sharktraits.org? 🤔

**Comment by creeas** [comment]
10-4 trying now

**Comment by creeas** [comment]
Boom that was it!

**Comment by coffeejunk** [comment]
💣 💣 

Okay, I'll set up redirects from sharktraits and globalsharktrends to sharkipedia, so this wont happen again.

**Comment by creeas** [comment]
Thanks for trouble shooting!
