### ISSUE TITLE
Allow resources to reference more than one species

### ISSUE THREAD

**Issue by coffeejunk** [sharkipedia/sharkipedia#16]
> There are a handful of studies that report traits for more than one species. Sometimes it is closely related species (such as the same genus) or it is form more distantly related species that are found sympatrically (a dogfish and a requiem shark). Didier and Capapé are two authors that have done this frequently.

**Comment by sebpardo** [comment]
Looking at the ERD I don't see why this is not currently the default behaviour of the database? In our previous iterations of our databases, as well as in Coral Traits, this is allowed by having a one-to-many relationship between Resource and Observation, so that you have a different observation for each species in a given publication/resource.

**Comment by sebpardo** [comment]
I should add that this would also allow for the cases where a paper compares traits for a single species from different locations (e.g. carlson2006 https://doi.org/10.1007/s10641-006-9129-x).

**Comment by coffeejunk** [comment]
> Looking at the ERD I don't see why this is not currently the default behaviour of the database? 

I was of the incorrect understanding that there could / should only be a 1-1 relation between resource and species, which is why it's not the current default.

**Comment by sebpardo** [comment]
> I was of the incorrect understanding that there could / should only be a 1-1 relation between resource and species, which is why it's not the current default.

That must have been confusing! The key aspect of the relationship between resource and observation (and hence species and location) is that each observation should link back to a single resource, thus allowing us to know precisely the resource where each measurement comes from.

So for a paper with multiple species, we have have separate observation for each species linking to the same resource, and likewise for a paper with one species at different location, we have a separate observation of the species for each location, all linking back to the one resource.
