### ISSUE TITLE
references

### ISSUE THREAD

**Issue by hkindsvater** [sharkipedia/sharkipedia#21]
Need to create list of "new" references so Chris can have them added to SharkReferences

**Comment by hkindsvater** [comment]
@creeas Here are the trends refs that are not in SharkReferences, but can be added
[refs to add.xlsx](https://github.com/coffeejunk/sharkT/files/3149450/refs.to.add.xlsx)

**Comment by coffeejunk** [comment]
Added in fee66d558d80a52f64f2dd4e048395c7c71b299d
