### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by hkindsvater** [sharkipedia/sharkipedia#24]
Write content for landing page for Traits 

- [ ] Search box? 
- [ ] description
- [ ] What logo/header do we want? 
- [ ] Funders and partners

**Comment by creeas** [comment]
Do we want the landing page to be the GUI/data explorer or a description page a la coraltraits? We could have an about homepage with an obvious link to the data explorer.

**Comment by hkindsvater** [comment]
@NickDulvy pointed out Froese and Pauly deliberately put the box up front with FishBase. And to be honest, I find Coral Traits' landing a rough - it's hard to find the data at the very top.

**Comment by hkindsvater** [comment]
@coffeejunk can you put together a simple landing page that allows someone to search/ filter the content by name/trait category? The search box (issue #26) is a key part of this. Then the page for each species will have all the info.

**Comment by NickDulvy** [comment]
The suggestion was that we would create family | genus | species search boxes with autocomplete. and then maybe a radio button for each of the 4 trait classes. This would then output something similar to the output of a search on the bottom of a FISHBASE search. e.g Genus Prionace.

![image](https://user-images.githubusercontent.com/5943202/58513363-28028300-8154-11e9-9a2f-c69f6e3c02b9.png)

Scroll down and click 'Age/Size' in the 'More information' table

![image](https://user-images.githubusercontent.com/5943202/58513424-47011500-8154-11e9-9cbe-dcaf97ca16d5.png)

![image](https://user-images.githubusercontent.com/5943202/58513437-541e0400-8154-11e9-9e32-4957d3b5ae2a.png)

**Comment by hkindsvater** [comment]
Great job resolving all these issues @coffeejunk @sebpardo
