### ISSUE TITLE
autocomplete box with searchable taxonomy for frontpage

### ISSUE THREAD

**Issue by hkindsvater** [sharkipedia/sharkipedia#26]
We need a way for people to search for species names (e.g., synonyms) that aren't in template.

**Comment by hkindsvater** [comment]
Fishbase interface might be a good model

**Comment by NickDulvy** [comment]
- [x] Let's focus on Fishbase style landing page, with autocomplete search boxes: Common Name, Genus, Species. This search would then yield a table with a list of all species.

- [ ] We should create a simple species page that would allow presentation of all available data for that species 

- [ ] Create similar for each trait or group of traits, this might be where we need to have further discussion on cross-table searches, i.e. generation time x genus = scyliorhinus.

- [ ] Add a feedback tab to middle of RHS of each page, see any Red List page. this would popup and email for the reader to complete and send to generic central email address. 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/5943202/57654372-da4d1e80-7588-11e9-9e2d-75603b296d03.png">

**Comment by NickDulvy** [comment]
Front page search boxes refined: 
- [ ] Drop Common name search for now 
- [ ] Have boxes for Family, Genus, Species
- [ ] create an autocomplete trait search bar
- [ ] This would need a link nearby to an FAQ page that lists the 4 trait classes & 45 or so traits

**Comment by coffeejunk** [comment]
I've removed the multi select boxes in favor of the direct selections as per the discussion of #33 

<img width="1353" alt="Screen Shot 2019-06-05 at 8 48 31 PM" src="https://user-images.githubusercontent.com/205556/58999327-48c17d00-87d3-11e9-8c6c-ff56463b1d7d.png">


Please let me know if you think there should be other searches on the front page.
