### ISSUE TITLE
Bug in species page rendering

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#292]
Hey @coffeejunk there appears to be something funky with the way the species pages are rendering after re-importing lots of the data. For example, when re-importing the data that Aaron compiled for Carcharhinids (https://www.sharkipedia.org/imports/93) the data from multispecies papers, such as White2007a looks fine in the entire upload (the excel window, the import log, and the total number of measurements from the home page) and in the reference page (https://www.sharkipedia.org/references/24406). But when we look at the Carcharhinus altimus species page (https://www.sharkipedia.org/species/691) there are tons of traits from white2007a, while on the ref landing page (https://www.sharkipedia.org/references/24406) it correctly shows that there are six traits for C. altimus from this reference. Not exactly sure what is going on here. Let me know if I can provide more info. Thanks!

**Comment by creeas** [comment]
This will potentially be an issue for Akshay's work as it pulls data from the species landing pages correct?

**Comment by coffeejunk** [comment]
@creeas Sorry, I'm a bit overloaded this week.. Will look at this during the weekend.

**Comment by creeas** [comment]
No worries at all @coffeejunk ! Thanks...
