### ISSUE TITLE
add generation length database in

### ISSUE THREAD

**Issue by NickDulvy** [sharkipedia/sharkipedia#37]
Add Peter Kyne generation length database when submitted/published. Need new trait column called generation length and maybe find a way to calculate new GL from existing data.

**Comment by sebpardo** [comment]
Unless the generation lengths are directly from a single published source (whether in a publication by PK or by the the original life history paper source) this is not a straightforward trait to add: generation length will be often estimated from traits in separate references, which is at odds with the "one-resource-per-trait" tenet. 

Ideally, we'd have the "raw" traits, with their respective resources, that were used to estimate GL and we can automatically calculate GL after they're added, or only include the GLs that come from single references.

**Comment by sebpardo** [comment]
Although I do agree, we should have a trait_name = "Generation length".

**Comment by hkindsvater** [comment]
@sebpardo good point, my understanding is Pete Kyne has a paper in the pipeline and these GLs will be published there and therefore citable. the milestone feature is to remind us this is a future addition.

**Comment by NickDulvy** [comment]
Let's make taht trait field and then we can either compute it or the space will be there when pete's paper is accepted.

**Comment by creeas** [comment]
I added generation length as a trait in the age trait class using the admin dashboard, thanks for that feature @coffeejunk . I just need to update the procedures document (Nick can you point to a resource that I can use to generate a description) and data entry template.

**Comment by coffeejunk** [comment]
@creeas can you also add the trait to the traits.csv file - keep in mind that the staging application is just a staging application and not the final public thing :)

**Comment by sebpardo** [comment]
@coffeejunk , so just to clarify, at this stage adding a new trait or standard is as simple as editing those csv files? Or is there more steps involved?

**Comment by creeas** [comment]
@sebpardo I used the admin dashboard `add trait` function b/c @coffeejunk said that once the database is deployed this is an easier route to go. If we modify the csv files then we have to redeploy the entire database each time.

**Comment by creeas** [comment]
@coffeejunk I've updated the traits template to include Generation Length in the Age trait class

**Comment by coffeejunk** [comment]
yup that's right. changes to the public application should be done through the admin dashboard. till we launch the application to the public we need to keep track of them in the csv files too.

**Comment by creeas** [comment]
@coffeejunk when we use the admin dashboard function does this automatically add that trait name to the list of acceptable trait names for the initial upload check?

Shall I add it to the csv file as well since it we are still pre-launch?

**Comment by coffeejunk** [comment]
@creeas it adds it to the checks but we also need it in the csv for the public launch.. so yes please :)

**Comment by creeas** [comment]
@coffeejunk done and done...
