### ISSUE TITLE
Tab/page menu not working properly in mobile browser

### ISSUE THREAD

**Issue by sebpardo** [sharkipedia/sharkipedia#39]
Hi @coffeejunk, As Bulma should be a mobile-oriented framework, I tried looking at both https://sharktraits.org/ and https://shark-t-staging.herokuapp.com/ from my mobile (Android S8 using Chrome). The rendering of the landing page looks fine, but the drop down menu in the top right (which has the three horizontal lines and should have the different pages, highlighted below) doesn't open up when I click it. Any thoughts of why this might be?

![Screenshot_20190611-101513_Chrome](https://user-images.githubusercontent.com/4634025/59275240-4ecfb780-8c32-11e9-9094-70a969f53f72.jpg)

**Comment by coffeejunk** [comment]
Interesting, nice catch. My guess would be that the order of the css classes isn't quite right or one is missing. Will have to investigate..
