### ISSUE TITLE
Adding metadata (description, common name, etc.) to species, traits, and standards

### ISSUE THREAD

**Issue by sebpardo** [sharkipedia/sharkipedia#40]
Right now the species.csv, traits.csv, and standard.csv are in wide format, where each column is a separate "class" of species, traits, and standard. For example, in species.csv each column is an order:

Chimaeriformes  | Batoidea  |	Squalimorph Sharks | Gaelomorph Sharks
-----|----|----|---
Callorhinchus callorynchus | Acroteriobatus omanensis  | Aculeola nigra | Alopias pelagicus
Callorhinchus capensis  |Acroteriobatus annulatus | Centrophorus atromarginatus  |Alopias superciliosus
Callorhinchus milii | Acroteriobatus blochii | Centrophorus granulosus | Alopias vulpinus
... | ... | ... | ...

The problem with this is that adding additional information for each species (for example, a common name to show in the species landing page) requires adding a second lookup csv file to match the species name with a common name, or in the case of trait or standard, with a description field.

I think it would be more straightforward to have these csv files in long format, where instead of having orders in each column you have a separate column for order, thus making it easier to add metadata in the same csv file:

Species  | Order | Common name
-----|----|---
Callorhinchus callorynchus | Chimaeriformes | American Elephantfish
Callorhinchus capensis  | Chimaeriformes | St. Joseph
Acroteriobatus omanensis  | Batoidea | Oman Guitarfish
Acroteriobatus annulatus | Batoidea | ...
Aculeola nigra | Squalimorph Sharks | ...
Centrophorus atromarginatus | Squalimorph Sharks  | ...
Alopias pelagicus | Gaelomorph Sharks  | ...
Alopias superciliosus | Gaelomorph Sharks | ...
... | ... | ...

Would switching the csv files used to import to this format be feasible? That way, we could easily add common names to species, and descriptions to traits and standards without the need of maintaining two separate files.

**Comment by coffeejunk** [comment]
Nope, ideally the CSV files will get deleted once we launch the application to the public. The only purpose they serve is to seed the database during development and launch. If you want to edit the metadata of species or whatever, this should be done via the Admin dashboard (of the launched application). 

The public-database should be seen as the one source of truth for data. The only reason why we're still doing anything with the CSV files is because we haven't pulled the trigger on the launch just yet.

**Comment by sebpardo** [comment]
I see. So how do you suggest we add additional information about species (e.g. common name and other info to populate the species landing pages) and traits/standards (description) now, before the public launch?

**Comment by coffeejunk** [comment]
If you want to add additional fields to _any_ data type (such as species) we first need a database migration that adds these fields to the respective tables (so we can store the information somewhere). With that in place you can either edit the models through the admin dashboard (ok for a couple, rather tedious for many) or I (or anyone else) can write an importer for whatever file format you choose.

With regards to pre- or post-launch, I don't think this matters really. We can bulk update existing items in the database or add new ones.. so if you create a CSV file that has 

| Species | Common name |
|----|----|
| Callorhinchus callorynchus | American Elephantfish |
| ... | ... |

I can easily write a script that updates the existing items in the database.

**Comment by sebpardo** [comment]
I guess the two outstanding this that need to be done now that the descriptions are uploaded are updating the traits page to include the descriptions from `traits-descriptions.csv` and add a page of descriptions for standards, methods, and models.
