### ISSUE TITLE
Resources Page on current staged trends app

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#53]
When searching the resources page for the most recent staged application that includes trends "more>Resources" there appears to only be resources for which data has been entered into the database. When you click on the 'show all references' link this still only shows a subset of all the resources in the master list. Additionally some of these resources only have a unique ID with no bibliographic information. The current live version (www.sharktraits.org) seems to be working properly and to include all bibliographic information. Just want to be sure that this functionality carries over, as users will need to able to search a reference to see if there is already a unique ID assigned.

**Comment by creeas** [comment]
<img width="1680" alt="Screen Shot 2019-10-04 at 2 35 46 PM" src="https://user-images.githubusercontent.com/4634830/66227806-54a34a00-e6b4-11e9-9a09-a897ba9853ba.png">
<img width="1680" alt="Screen Shot 2019-10-04 at 2 35 57 PM" src="https://user-images.githubusercontent.com/4634830/66227830-6258cf80-e6b4-11e9-9361-bd2ccbabf961.png">

**Comment by hkindsvater** [comment]
Related comment - the link (on the staging app) that says "To add a new reference/resource please click here"  goes to the main page, not the Reference/resource page. But maybe that is only wonky in the staging app? It is not easy to know what references are already in the database unless you know the authoryear code. It would be worth brainstorming some ways to make that process smoother.

**Comment by coffeejunk** [comment]
Just to clarify, the staging and the live application have separate, independent databases.
Since the references are imported once (when the application and it's database got created) from a csv file and then land in the database, the applications will diverge in what data they present as soon as anyone starts making any edits. Which is kind of the point, so we can "mess around" with new features in staging before we push them out to the real world.

That said, I'll pull the changes "down" from production to staging so we have better data to mess with.

**Comment by coffeejunk** [comment]
> Related comment - the link (on the staging app) that says "To add a new reference/resource please click here" goes to the main page, not the Reference/resource page. But maybe that is only wonky in the staging app?

@hkindsvater on which specific page is this happening? Both the link in the Trait as well as in the Trend form is working properly for me 🤔 

> It is not easy to know what references are already in the database unless you know the authoryear code. It would be worth brainstorming some ways to make that process smoother.

True, we could add a proper search/interface for the references.

**Comment by coffeejunk** [comment]
@creeas FYI I've updated the staging database to reflect the latest version of the production database. So all the fixed resources and data that is in production is now also in staging. That said the databases behind the two application are distinct, so if you make changes to the data in the live application the staging application will not reflect these changes.

**Comment by hkindsvater** [comment]
@coffeejunk thanks for the updates. Also, FYI I am not having the issue above (Please click here going to the wrong page) anymore!
