### ISSUE TITLE
Trait entry interface and new species

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#55]
The web based traits entry portal will need an option for entering data from a 'newly described' species as laid out in the procedures document.

**Comment by coffeejunk** [comment]
New species can be added to the database via the admin dashboard at `/admin/species/new` or would this procedure require any additional steps besides just the creation of a new species?

**Comment by creeas** [comment]
In the template we have a "newly described species" option, to allow users to import valid data that will be embargoed until the species is formally described and can be added to the master taxonomy. I was thinking we could have this same functionality for the web interface as well. Then once the formal description comes out an admin can add it via the dashboard and lift the embargo on the data.

**Comment by coffeejunk** [comment]
Ah gotcha. I think the easiest way to do this is to simply add a dummy "newly described species" species, which then gets changed to the proper one later.

**Comment by creeas** [comment]
Yeah that's exactly what I was thinking. That is already in the template and I will check the taxonomy csv to make sure it is there.
