### ISSUE TITLE
Age of larger immature

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#56]
Track down and remove "Age of larger immature" from original data upload. Change trait name to "Age of largest immature" following data clean-up and prior to relaunch.

**Comment by coffeejunk** [comment]
>  following data clean-up and prior to relaunch.

The only necessary step here should be to rename [the trait](https://www.sharktraits.org/admin/traits/20). All other data-sets only reference this trait in the database. Once you update the name, the interface and everything else will also be updated.

**Comment by creeas** [comment]
Awesome thanks @coffeejunk
