### ISSUE TITLE
New References Entry Template

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#66]
Hey @coffeejunk can we tweak the "New References" entry template to mimic the more standard entry form for reference software such as endnote or mendeley (see image). So users would enter the required reference information:
Authors
Year
Title
Journal Name
Vol #
Pages

And then the author year code would be automatically generated following the rules established, and the suffix would be automatically generated after the db checks for similar author year codes already assigned (e.g. Dulvy2014, Dulvy2014a). I think automatically generating these codes would save potential issues that would arise if users designated them manually.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/4634830/67241549-015a2700-f42a-11e9-8273-5a994afc0b38.png">

**Comment by coffeejunk** [comment]
Yep, will do.

**Comment by hkindsvater** [comment]
Thanks @creeas and @coffeejunk but we need a line for the doi too right?

**Comment by coffeejunk** [comment]
> author year code would be automatically generated following the rules established

@creeas do we have these rules codified somewhere? 

for example in your screenshot, you have five authors, which results in what code? `last name of the first author+year` or should it be the `last names of the first two authors, joined + year`?

**Comment by coffeejunk** [comment]
@creeas ping

**Comment by sebpardo** [comment]
It should be last name of first author + year, with the letters a, b, c, etc. appended to this if the combination of author + year (+ letter) is already in use.

**Comment by coffeejunk** [comment]
@sebpardo ok, that's easy enough then. Thanks!

**Comment by creeas** [comment]
Sorry I missed you question @coffeejunk , thanks @sebpardo for answering!
