### ISSUE TITLE
Trait Entry Interface

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#67]
Hey @coffeejunk we had a chat today and are hoping to make a few changes to the trait entry web interface to make it easier for users. 

1. It would be helpful to indicate which fields are needed to meet the minimum requirements for data inclusion. At the observation level we require `contributor_ID`, `Access`, `species`, and `reference`. Fortunately these won't require much else as the `contributor_ID` is automatically generated and `Access` is default to public. The `species` and `reference` fields are very clear at the top of the page. For measurements the minimum required fields are `sex`, `trait class`, `trait name`, `value`, and `standard`. Signifying these with a red asterisk or other marker (such as in filling out cc info online) would be useful. 

2. The references field works really well and it's very slick that it updates to show the full bibliographic information when you enter the author year and can verify the correct reference id. Can we add some way of denoting if a reference has already been entered into the db? Currently the only way to check this is under the more>references tab and then toggling between "show all references" and "show only references with data". Could we add an additional row for data entered with a yes or no in the field accordingly?

<img width="1479" alt="Screen Shot 2019-10-21 at 6 02 30 PM" src="https://user-images.githubusercontent.com/4634830/67243906-fd7cd380-f42e-11e9-9dc8-4119c7afd3eb.png">

3. Can we reorganize the fields in the measurement entry area to follow the natural hierarchy of the data? When we built the template to fill we organized the columns in the measurement-level section to reflect this, and then built in a series of hierarchical restrictions from there. So when a user designated a length as the `trait class` the drop down menu for trait would only include traits from that class, and the same for standards, methods, and models. 

<img width="313" alt="Screen Shot 2019-10-21 at 5 48 26 PM" src="https://user-images.githubusercontent.com/4634830/67244159-872ca100-f42f-11e9-804e-37248db3a66d.png">

This avoids humongous drop down menus that have to be navigated every time. As you can see currently the measurement entry template does not include `trait class` which makes this structure difficult. In this example I have selected Lmat50, but the standards drop down list includes lots of inappropriate choices. If users accidentally select the wrong one here this will be a pain to correct.

<img width="1680" alt="Screen Shot 2019-10-21 at 5 47 11 PM" src="https://user-images.githubusercontent.com/4634830/67244483-2baee300-f430-11e9-8822-34bac5c3fc22.png">

The hierarchical restrictions are built into the template using the values tab, but this should be able to follow along from the csv tables within the database. Let me know if you need me to provide you anything the help with this.

4. Can we set it up so that the current admin team receives notifications for web entry data once per week or so? This way we won't get a bunch of e-mails for every single data measurement upload!

Let me know how I can help with all this too...

**Comment by coffeejunk** [comment]
@creeas Pt 1-3 are implemented and live (https://shark-t-staging.herokuapp.com/observations/new | https://www.sharktraits.org/observations/new) I've extraced Pt 4 into #73 since it's not strictly related to the interface.
