### ISSUE TITLE
'New Mass Import' link not working

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#89]
@coffeejunk my student (ajudah) is having trouble with accessing the new mass import page. When he is logged in and clicks on 'Upload Data > New Mass Import' is takes him back to the homepage. Same when he tries to enter the URL 'https://www.sharktraits.org/imports/new' manually it still redirects him the homepage. Not sure if this issue is the same for everyone in the 'user' category. I am logged in as admin and it seems to be working fine for me.

**Comment by coffeejunk** [comment]
@creeas he should be able to access it now.

**Comment by coffeejunk** [comment]
there is (currently) a restriction for users to be on the `contributor` level.

**Comment by creeas** [comment]
Great thanks. So will we be required to upgrade `users` to `contributors` to allow uploads?

**Comment by coffeejunk** [comment]
For the moment, yes. We can change this to be just `user` easily, but we're getting _a lot_ of spam sign ups at the moment, so I'd want to address that first. :\

**Comment by creeas** [comment]
Oh good call. I think manually designating contributors is fine for the moment. We don't want to be overrun by bots!
