### ISSUE TITLE
Allow users to make their uploaded data public

### ISSUE THREAD

**Issue by coffeejunk** [sharkipedia/sharkipedia#9]

**Comment by sebpardo** [comment]
I think that, at least for Shark Traits, we need to have the default for data to be public, and only an option to hide the data ("hidden" boolean in the Observation table). 

The other field we are missing in relation to making data public is related to the curation aspect of the database. Data should not be made public immediately after they have been uploaded by the contributor, but only after it has been checked by an editor. What do you think is the best way to incorporate this?

**Comment by coffeejunk** [comment]
> Data should not be made public immediately after they have been uploaded by the contributor, but only after it has been checked by an editor.

this is not happening.. The import flow is:

1. User uploads
2. Automatic validations take place (eg. is the excel sheet malformed)
3. If the validations pass, editors/admins are notified who can then check the data and either reject, request changes or approve
4. Once approved the actual import takes place

Now if the data in the excel sheet has the `hidden = 1` flag set, we need an extra step for the uploading user to make the data publicly accessible

**Comment by sebpardo** [comment]
Oh, I see what you mean, I agree that having that extra step is important. I'm sorry about the confusion!
