### ISSUE TITLE
Marine region layer

### ISSUE THREAD

**Issue by natpac** [sharkipedia/sharkipedia#96]
Hi Max,
So the common code between the shp I sent you and the online shp you are currently using for the Marine Ecoregions (PPOW/MEOW) are respectively: 'Type_provi' and 'PROVINC'. To note, ' Type_provi' has extra characters at the beginning : 'PPOW_' or 'MEOW_', then the rest should be the same. Let me know if this doesn't work.
I also found a [link](http://www.fao.org/geonetwork/srv/en/main.home) to the FAO major areas and they give a link to OGC-WMS Server in the 'Distribution Information' section. Let me know if this is what you needed.
Cheers,

**Comment by coffeejunk** [comment]
Regarding FAO, would this be `FAO Statistical Areas for Fishery Purposes`?

**Comment by natpac** [comment]
Yes sorry, I didn't realise the link only refer to the home page...

**Comment by natpac** [comment]
Is it possible to display only 'F_areas' for the FAO statistical areas?
