### ISSUE TITLE
Trends -> excel type display

### ISSUE THREAD

**Issue by natpac** [sharkipedia/sharkipedia#97]
Hi,
I don't know how feasible it is but would it be possible to have the 'Search species information table' as in this [shinyapp](https://rossdwyer.shinyapps.io/sharkray_mpa/)? I like the way you can filter by columns, and enter/filter data.
Maybe we can display only a subset of the column (hide the rest), like 'Family', 'Genus', 'Species', 'AuthorYear', 'Source_observation', 'General_data_type', 'Sampling_method_general', 'Dataset_location', 'Ocean'. I don't know if we need the values in this display table, or the coastal and pelagic provinces. Maybe in the future, we could add above this table the global map with the coastal and pelagic provinces, and FAO areas, and make the ones selected when the table is filtered highlighted.
The option to show a certain number of entries could be 10-50-all, or just no option and it displays all.

Any thoughts?

**Comment by coffeejunk** [comment]
Done as of #108
